### PR TITLE
Documentation enhancement

### PR DESCRIPTION
**Pull request by BenWiederhake**
You may (in case my pull requests are bothering you) just leave this pull request open for a while.

### CODE REVIEW

**Comment by raffienficiaud** [comment]
you can maybe group it with some other commits...

**Comment by BenWiederhake** [comment]
There are no other commits (yet?), and I'm not sure whether I will find more. That's why I'm doing this pull request now, instead of "later when I'm done".

**Comment by raffienficiaud** [comment]
So let's leave it open for some time just in case you find other typos. Thanks!

**Comment by BenWiederhake** [comment]
That's a good idea :)

**Comment by BenWiederhake** [comment]
(Also, see my mail; unrelated and long)

**Comment by raffienficiaud** [comment]
I did not know about that, please fill a ticket on trac.

**Comment by BenWiederhake** [comment]
In case anyone else is reading this: See https://svn.boost.org/trac/boost/ticket/11582

**Pull request merged**
