### PR TITLE
fix uninitilized variable in framework_init_observer_t

### PR DESCRIPTION
**Pull request by K-os**
fixes: #272

### CODE REVIEW

**Comment by vakatov** [comment]
Did this fix fall through the cracks? It fixes problem for us but... still not in the releases. Without the fix, we are stuck with 1.72.0 (or, internally, with patched Boost 1.73.0+).

**Comment by K-os** [comment]
I think this project is dead.

The number of open issues is growing and the only ones closed in the last year were closed by the reporters themselves. Also no PRs were merged for over a year.

**Comment by raffienficiaud** [comment]
The project is not dead.

**Comment by vakatov** [comment]
Are there plans to deal with this bug? It was identified 1.5 years ago, and it clearly affects more than one user.

**Comment by raffienficiaud** [comment]
Yes, the CI was dead since I moved from my previous job and now I fixed it. Travis and Appveyor are just not working.
I will fix the current issues on develop and run the CI on this one. This should be done in the next couple of days.

**Comment by raffienficiaud** [comment]
Fixed through #328 rev 194a69e

**Comment by raffienficiaud** [comment]
Thank you for the patch!

**Comment by vakatov** [comment]
Great, thanks much @K-os and @raffienficiaud!

**Comment by K-os** [comment]
Good to see progress in this project. Thanks for maintaining it.

**Pull request closed without merging**
