### PR TITLE
Update config.hpp

### PR DESCRIPTION
**Pull request by akumta**
For ticket# 6766

### CODE REVIEW

**Comment by raffienficiaud** [comment]
Hi,

Would you please tell me if the branch tractickets/6766-incorrect-declaration-for-putenv-in-config.hpp corrects the issue?
I rebased your patch onto 0f34822 

Thanks,
Raffi

**Comment by akumta** [comment]
I'm not clear on what needs to be verified.
I looked at
https://github.com/boostorg/test/commit/0f95ca8896647d324f2131d9cb20d292d4ca6a80
 and it looks OK.
If I need to check on something else, do let me know. I will do so.

Thanks.

**Comment by raffienficiaud** [comment]
The idea is that you checkout this branch ``tractickets/6766-incorrect-declaration-for-putenv-in-config.hpp `` and test it. I added some changes to your PR.

**Comment by akumta** [comment]
I'm not familiar with git. How do I check out this branch?
Could you point me to some documentation on it, if possible?

Thanks.

**Comment by raffienficiaud** [comment]
Let's call `$boost` your boost clone:

```
cd libs/test
git fetch
git checkout tractickets/6766-incorrect-declaration-for-putenv-in-config.hpp
```

**Comment by akumta** [comment]
Thanks, I will clone the repository and follow the steps, test and report back here.

**Comment by raffienficiaud** [comment]
Ok thanks. If you clone, you have to do the following before the commands I sent above

```
git clone https://github.com/boostorg/boost.git
git submodule init
git submodule update --recursive
```

**Comment by akumta** [comment]
Yes, will do. Thanks.

**Comment by akumta** [comment]
I have tested the changes. It looks good. Thanks.

**Comment by raffienficiaud** [comment]
Thanks, I merge the changes to develop once we have a slot.

**Comment by akumta** [comment]
Thank you, truly appreciate your help on this ticket(#6766). It has been around for 3 years and getting this into 1.58 would mean around 15% improvement in the pass rate for the test runs with our compiler.

**Comment by akumta** [comment]
Any idea when the slot would be open to merge?

**Comment by raffienficiaud** [comment]
Merged to develop

**Pull request closed without merging**
