### PR TITLE
Using type_index to avoid all RTTIs. (fixes #9228)

### PR DESCRIPTION
**Pull request by gongminmin**
A better solution than #ifndef BOOST_NO_RTTI.

### CODE REVIEW

**Comment by rogeeff** [comment]
I'm not sure we want to introduce new dependency for Boost.Test.

On Wed, Mar 4, 2015 at 12:53 AM, Minmin Gong <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/boostorg/test/pull/38
> Commit Summary
>
>    - Using type_index to avoid all RTTIs. (fixes #9228)
>
> File Changes
>
>    - *M* include/boost/test/execution_monitor.hpp
>    <https://github.com/boostorg/test/pull/38/files#diff-0> (13)
>    - *M* include/boost/test/tree/test_case_template.hpp
>    <https://github.com/boostorg/test/pull/38/files#diff-1> (13)
>    - *M* include/boost/test/utils/runtime/interpret_argument_value.hpp
>    <https://github.com/boostorg/test/pull/38/files#diff-2> (3)
>    - *M* test/test_datasets_src/test_datasets.hpp
>    <https://github.com/boostorg/test/pull/38/files#diff-3> (3)
>
> Patch Links:
>
>    - https://github.com/boostorg/test/pull/38.patch
>    - https://github.com/boostorg/test/pull/38.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boostorg/test/pull/38>.
>



-- 
Gennadiy Rozental

**Comment by raffienficiaud** [comment]
The issue 9228 is already fixed in develop. Any other motivation behind the changes you propose?

**Comment by gongminmin** [comment]
That fix uses #ifdef to separate RTTI on and off. If we switch to type_index, we can have a unified code.

**Comment by raffienficiaud** [comment]
Ok, but this is rather cosmetic than a fix to an identified problem. The issue 9228 has already been addressed.

**Pull request closed without merging**
