### PR TITLE
Update fwd.hpp

### PR DESCRIPTION
**Pull request by akumta**
Possible solution for #11347.

### CODE REVIEW

**Comment by rogeeff** [comment]
Maybe let's name this type Dataset

On Tue, May 26, 2015 at 2:14 PM, akumta <notifications@github.com> wrote:

> Possible solution for #11347.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/boostorg/test/pull/67
> Commit Summary
>
>    - Update fwd.hpp
>
> File Changes
>
>    - *M* include/boost/test/data/monomorphic/fwd.hpp
>    <https://github.com/boostorg/test/pull/67/files#diff-0> (40)
>
> Patch Links:
>
>    - https://github.com/boostorg/test/pull/67.patch
>    - https://github.com/boostorg/test/pull/67.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boostorg/test/pull/67>.
>



-- 
Gennadiy Rozental

**Comment by raffienficiaud** [comment]
Hi Aparna,

Would you please rename the `D_S` to `Dataset`. Then we would merge your changes. Do you confirm that is solves (some of the) issues on Sun?

**Comment by akumta** [comment]
How do i update this without submitting another PR?

**Comment by akumta** [comment]
Renamed the D_S to Dataset

**Comment by raffienficiaud** [comment]
Thanks, do you confirm that is solves your issue on Sun, we are unable to test this directly.

**Comment by akumta** [comment]
Yes, this change does resolve this particular issue. Thanks for getting this in.

**Pull request merged**
